### PR TITLE
Allow to manage target part of the module

### PR DESCRIPTION
**Pull request by ArVincentr**
Hi, 

This PR is related to issue #123. I added the part to manage the target part, simple yet to enhance wherever needed.

best regards

### CODE REVIEW

**Comment by jordiprats** [comment]
Hi,
I not comfortable with having the [Unit] section duplicated on the target an [service](https://github.com/jordiprats/eyp-systemd/blob/master/templates/service.erb) templates. This also happens, for example, on the [socket](https://github.com/jordiprats/eyp-systemd/blob/master/templates/socket.erb) and [timer](https://github.com/jordiprats/eyp-systemd/blob/master/templates/timer.erb) templates, I feel we should be rewriting this using a concat::fragement for each section

On the other hand, I don't understand why you are using the service namespace, shouldn't it have it's own target namespace (systemd::target instead of systemd::service::target)

thanks,

**Comment by ArVincentr** [comment]
Hi,
I saw the the target as a dependency. but no problem I can split and create its own namespace.

as to the concat part, I'll review it as well.

Regards

**Comment by jordiprats** [comment]
I have started modiying the other templates on my [own fork](https://github.com/jordiprats/eyp-systemd)

You can take a look at the [differences](https://github.com/NTTCom-MS/eyp-systemd/compare/master...jordiprats:master) for more details

kind regards,

**Comment by ArVincentr** [comment]
Hi,
thanks for the update. I checked your work and adapted mine. target has its own namesapce and I prepared the part to work with concat too  but I can't ask for a merge request as your commits are done in your topic branch. 
What would be the next step to make it to progress ? 

for ex. in the /section/unit.erb the parameter allowisolate is missing which I can't add myself.

Regards

**Comment by jordiprats** [comment]
Hi,
I've added AllowIsolate as allow_isolate on my side on my [latest commit](https://github.com/jordiprats/eyp-systemd/commit/90bb3e406b34bb71344c80acce8c0a3d4f15813e)

The idea behind this naming convention is to have templates more similar to the [timer template](https://github.com/jordiprats/eyp-systemd/blob/master/templates/section/timer.erb)

If you could please change the variable with the underscore I'm going to merge it to my repo, perform some testing and then merge it back to the main one.

thanks,

**Comment by ArVincentr** [comment]
Hi,

Thanks for the fast reply :) I have changed the variable as requested.

Kind regards

**Comment by jordiprats** [comment]
Hi,
This PR have been merged in the [0.2.0 release using PR-127](https://github.com/NTTCom-MS/eyp-systemd/pull/127).

I've added on the CHANGELOG credit for your work and a reference for this PR

Thank you for all your work on this!

**Pull request closed without merging**
