### PR TITLE
systemd::timer camelcase + nil values

### PR DESCRIPTION
**Pull request by cedef**
This is related to @func0der's suggestion about changing the `timer.erb` template, in #44:
> The loop in the template, which only converts the first letter to upper case, needs to be changed to convert underscore_writing to UpperCamelCase.

- When passing `on_calendar => '06:00:00'` ERB template would produce
  `On_calendar=`.. instead of `OnCalendar=`.
- Moreover, all undef values were unset because of the var.to_s != 'undef' which
  does not work with Puppet4. The file was full of unassigned directives like
 `/^OnBootSec=$/`
- Added spec tests using rspec-puppet-facts to loop over supported OS and spec
  tests for systemd::timer defined type

### CODE REVIEW

**Comment by cedef** [comment]
I think the `timer.rb` spec acceptance probably contains a mistake on line `37`: file content is tested against the `on_boot_sec` string instead of `OnBootSec`.
Although I'm not familiar with acceptance tests... so I might be wrong.

**Comment by func0der** [comment]
Did you try your `scope[variableName].nil?` against Puppet 3?
I remember to had it just like that and it did not work. I am not 100% sure though.

Thanks for doing this. I had absolutely no time ^^

**Comment by cedef** [comment]
Based on spec test with PUPPET_VERSION=3.8.7, here is the [output](https://github.com/NTTCom-MS/eyp-systemd/files/1054317/puppet3-build.txt): all green light. So it should be ok :)

Regards,

**Comment by jordiprats** [comment]
I'm loving the way you are converting underscore_writing to UpperCamelCase!

Thanks for your copntribution!

**Comment by cedef** [comment]
> I'm loving the way you are converting underscore_writing to UpperCamelCase!

Thank you :)

> Thanks for your contribution!

You're welcome !

**Pull request merged**
